### ISSUE TITLE
groups are not created with KeyError

### ISSUE THREAD

**Issue by TheKoguryo** [oracle-quickstart/oci-landing-zones#12]
When deploying OELZ in Resource Manager, the groups are not created with the following errors.

```
module.nonprod_environment.module.identity.module.identity_domain.null_resource.groups[0]: Provisioning with 'local-exec'...
module.nonprod_environment.module.identity.module.identity_domain.null_resource.groups[0](local-exec): Executing: ["/bin/sh" "-c" "python3 scripts/manage_identity_domain.py -d ocid1.domain.oc1..aaaaaaaareguouqp7c7p75prwglvpszq47h6rhepbzmrhacf3nl7cyi5qzea -g OCI-ELZ-UGP-N-APP-ADMIN OCI-ELZ-UGP-N-DB-ADMIN OCI-ELZ-UGP-N-IDP-ADMIN OCI-ELZ-UGP-N-NET-ADMIN OCI-ELZ-UGP-N-OPS-ADMIN OCI-ELZ-UGP-N-PLT-ADMIN OCI-ELZ-UGP-N-SEC-ADMIN OCI-ELZ-UGP-N-WRK-ADMIN"]
module.nonprod_environment.module.identity.module.identity_domain.null_resource.groups[0] (local-exec): Traceback (most recent call last):
module.nonprod_environment.module.identity.module.identity_domain.null_resource.groups[0](local-exec):   File "scripts/manage_identity_domain.py", line 127, in <module>
module.nonprod_environment.module.identity.module.identity_domain.null_resource.groups[0] (local-exec):     manage_id = ManageIdentityDomain(args.domain_id, args.group_names)
module.nonprod_environment.module.identity.module.identity_domain.null_resource.groups[0](local-exec):   File "scripts/manage_identity_domain.py", line 14, in __init__
module.nonprod_environment.module.identity.module.identity_domain.null_resource.groups[0] (local-exec):     self.config, self.auth = self.set_up_oci_config()
module.nonprod_environment.module.identity.module.identity_domain.null_resource.groups[0](local-exec):   File "scripts/manage_identity_domain.py", line 29, in set_up_oci_config
module.nonprod_environment.module.identity.module.identity_domain.null_resource.groups[0] (local-exec):     user=config['user'],
module.nonprod_environment.module.identity.module.identity_domain.null_resource.groups[0] (local-exec): KeyError: 'user'
module.nonprod_environment.module.identity.module.identity_domain.null_resource.groups[0]: Creation complete after 2s [id=625788031282522014]
```

After rewriting the following file(modules/identity-domain/scripts/manage_identity_domain.py) to change a signer, it works for me.

```
class ManageIdentityDomain:
    def __init__(self, domain_id, group_names):
        self.config, self.auth = self.set_up_oci_config()
        self.identity_client = oci.identity.IdentityClient(config=self.config, signer=self.auth)

        self.host = self.get_domain_url(domain_id)
        self.group_endpoint = self.host + "/admin/v1/Groups"
        self.group_names = group_names

    def set_up_oci_config(self):
        '''
        check terraform environment variables, prefixed by TF_, so it can run in our pipeline
        '''
        try:
            config = {}
            obo_token = os.environ.get("OCI_obo_token")
            auth = oci.auth.signers.InstancePrincipalsDelegationTokenSigner(delegation_token=obo_token)

        except Exception as e:
            print(f"set_up_oci_config")
            print(e)

        return config, auth
```

**Comment by paulmuah** [comment]
Resolved by @VinayKumar611

**Comment by jmalbarranORA** [comment]
Hi,
Is the issue solution commited? I'm having the same issue.
I'm trying to apply the solution suggested, but I do not know how to "redeploy" correctly
I have tried
`terraform apply -replace=nonprod_environment.identity_domain --var-file demolandingzonev2.tfvars `

**Comment by jmalbarranORA** [comment]
UPDATE
The groups are not created because the creation scripts is reading default config file with default profile, and, in my case, no DEFAULT profile.
I have just temporally solved hard-coding the profile
`oci.config.from_file(profile_name="DEMOLANDINGZONEV2")`

but the correct solution is to build the config using the variables
config = {
    "user": "<your_user_ocid>",
    "key_file": "<full_path_to_your_private_key>",
    "fingerprint": "<fingerprint_of_your_public_key>",
    "tenancy": "<your_tenancy_ocid>",
    "region": "<your_oci_region>"
}

I assume that the problem only happens executing in local PC with multiple profiles, and not in ORM
